'use client';
/* oxlint-disable next(no-html-link-for-pages) */

import { useState, type FormEvent } from 'react';
import { ArrowRight, Languages, LoaderCircle, LockKeyhole, Sparkles } from 'lucide-react';
import { useLanguage,type Language } from './i18n';

export default function AuthForm({mode}:{mode:'login'|'register'}) {
  const {language,setLanguage,t}=useLanguage();const [error,setError]=useState('');const [busy,setBusy]=useState(false);const registering=mode==='register';
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);const response=await fetch(`/api/auth/${mode}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:form.get('name'),email:form.get('email'),password:form.get('password')})});const payload=await response.json().catch(()=>({})) as {error?:string};if(response.ok){window.location.assign('/');return}setError(payload.error||t('somethingWrong'));setBusy(false)}
  return <main className="auth-shell"><section className="auth-card"><div className="auth-card-top"><a className="auth-brand" href="/"><span className="brand-mark"><Sparkles size={18}/></span><strong>schwank</strong></a><label className="language-switch"><Languages size={15}/><select value={language} onChange={event=>setLanguage(event.target.value as Language)} aria-label={t('language')}><option value="en">EN</option><option value="ru">RU</option></select></label></div><div className="auth-icon"><LockKeyhole size={22}/></div><span className="eyebrow">{t('privateWorkspace')}</span><h1>{registering?t('createAccount'):t('welcomeBack')}</h1><p>{registering?t('registerCopy'):t('loginCopy')}</p><form onSubmit={submit}>{registering&&<label><span>{t('yourName')}</span><input name="name" autoComplete="name" minLength={2} maxLength={40} required/></label>}<label><span>{t('email')}</span><input name="email" type="email" autoComplete="email" maxLength={254} required/></label><label><span>{t('password')}</span><input name="password" type="password" autoComplete={registering?'new-password':'current-password'} minLength={12} maxLength={128} required/><small>{registering?t('passwordHint'):''}</small></label>{error&&<div className="auth-error" role="alert">{error}</div>}<button className="primary-button auth-submit" disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<>{registering?t('createAccount'):t('signIn')}<ArrowRight size={17}/></>}</button></form><footer>{registering?t('alreadyAccount'):t('newHere')} <a href={registering?'/login':'/register'}>{registering?t('signIn'):t('createAnAccount')}</a></footer></section></main>;
}
