'use client';

import { useState, type FormEvent } from 'react';
import { ArrowRight, LoaderCircle, LockKeyhole, Sparkles } from 'lucide-react';

export default function AuthForm({mode}:{mode:'login'|'register'}) {
  const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const registering=mode==='register';
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const form=new FormData(event.currentTarget);const response=await fetch(`/api/auth/${mode}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:form.get('name'),email:form.get('email'),password:form.get('password')})});const payload=await response.json().catch(()=>({error:'Something went wrong.'})) as {error?:string};if(response.ok){window.location.assign('/');return;}setError(payload.error||'Something went wrong.');setBusy(false);}
  return <main className="auth-shell"><section className="auth-card"><a className="auth-brand" href="/"><span className="brand-mark"><Sparkles size={18}/></span><strong>schwank</strong></a><div className="auth-icon"><LockKeyhole size={22}/></div><span className="eyebrow">Private household workspace</span><h1>{registering?'Create your account':'Welcome back'}</h1><p>{registering?'Your private data stays yours. You choose what to share with the household.':'Sign in to your private corner of the household.'}</p><form onSubmit={submit}>{registering&&<label><span>Your name</span><input name="name" autoComplete="name" minLength={2} maxLength={40} required autoFocus/></label>}<label><span>Email</span><input name="email" type="email" autoComplete="email" maxLength={254} required autoFocus={!registering}/></label><label><span>Password</span><input name="password" type="password" autoComplete={registering?'new-password':'current-password'} minLength={12} maxLength={128} required/><small>{registering?'Use at least 12 characters.':''}</small></label>{error&&<div className="auth-error" role="alert">{error}</div>}<button className="primary-button auth-submit" disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<>{registering?'Create account':'Sign in'}<ArrowRight size={17}/></>}</button></form><footer>{registering?'Already have an account?':'New to schwank?'} <a href={registering?'/login':'/register'}>{registering?'Sign in':'Create an account'}</a></footer></section></main>;
}
